### ISSUE TITLE
Getting an Error "AttributeError: 'dict' object has no attribute 'encode'"

### ISSUE THREAD

**Issue by mady143** [ranjaykrishna/iq#6]
Hi @ranjaykrishna ,

i am trying to execute python utils/vocab.py getting an error 
**"Traceback (most recent call last):
  File "utils/vocab.py", line 144, in <module>
    vocab = build_vocab(args.questions, args.cat2ans, args.threshold)
  File "utils/vocab.py", line 93, in build_vocab
    answer = tokenize(answer.encode('utf8'))
AttributeError: 'dict' object has no attribute 'encode'"**

can you help me to resolve this issue...

Thanks & Regards,
Manikantha Sekhar...

**Comment by 13vida37** [comment]
g
